baseURL = 'https://izaac.mammadov.co.uk'
languageCode = 'en-gb'
title = "Izaac's Website"
theme = 'lugo'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Relevant Tags:"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
